<?php

 header("ContentType: text/xml");
 $pins = array( "1" =>'B');
 
 
 
 $item1 = "<title>The value of the pin is {$pins[1]} </title><description>Reading pin 1</description>".
          "<link>http://localhost/~gary/</link>";
 
 echo '<?xml version="1.0"?>';
 
 echo '<rss version="2.0">';
 echo '<channel>';
 echo '<title>Arduino Php Rss</title>';
 echo '<description>A test RSS feed generated by php</description>';
 echo '<link>http://localhost/~gary</link>';
 
 echo '<item>';
 echo $item1;
 echo '</item>';
 echo '</channel>';
 
 echo '</rss>';

?>